### PR TITLE
Load new MPU-9255

### PR DESCRIPTION
**Pull request by Nick-Currawong**
Hi Richard,

I have added the definitions for a IvenSense MPU-9255 IMU.

The only difference I can see was the location address changed from the MPU-9250 (0x71) to MPU-9255 (0x73).

Hope it helps someone.

### CODE REVIEW

**Comment by r-b-us** [comment]
Problem is that I can't test it and even RTIMULib2 really isn't supported any more as I have moved on to other things.

**Comment by r-b-us** [comment]
I could put an entry on my blog pointing to your implementation for those interested in the MPU-9255. Would that be useful?

**Comment by Nick-Currawong** [comment]
Hi Richard,
I guess a entry in your blog, would be good. I understand you would not be able to test (can't have every piece of kit which comes on to the market). 
Your RTIMULib does seem to get used (mentioned) in lots of places, a good piece of useful work.

Thanks

**Comment by sailoog** [comment]
> Your RTIMULib does seem to get used (mentioned) in lots of places, a good piece of useful work.

+1

**Pull request closed without merging**
